### ISSUE TITLE
There should be Quit button on sign in screen

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-desktop#1]
There is no Quit option on sign in screen. There should be.

![Screen Shot 2020-04-15 at 10 55 39](https://user-images.githubusercontent.com/3696314/79312580-c3851980-7f07-11ea-8a8f-073ab1aa58c8.png)

**Comment by oguzhaninan** [comment]
Done 👍

**Comment by yakuter** [comment]
Tested it, seems great. Thank you.
